[package]
name = "swarm-player-server"
version = "1.0.0"
description = "Server app for Swarm Player"
authors = ["ern0 <ern0@linkbroker.hu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-websockets = "0.1.5"